version: '3.1'
services: 
  web:
    build:
      context: .
      args:
        client_image_name: ${client_image_name}
    container_name: ${app_name}
    image: ${app_name}:${app_build_version}
    restart: always
    volumes:
      - /data/${app_name}/files:/usr/share/nginx/html/files
    ports:
      - "${app_port}:443"
  server:
    image: "${server_image_name}"
    container_name: ${app_name}_server
    restart: always
    volumes:
      - /data/${app_name}/files:/app/files
      - /data/${app_name}/configs:/app/configs
    environment:
      BackendService: "true"
      CorsOrigins: "${app_CorsOrigins}"
      DefaultPassword: "${app_init_pwd}"
  db:
    image: mariadb
    container_name: ${app_name}_db
    restart: always
    volumes:
      - /data/${app_name}/db:/var/lib/mysql
    ports:
      - "${app_db_port}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${app_db_pwd:-123456}
