// source: keyvalues.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var messages_pb = require('./messages_pb.js');
goog.object.extend(proto, messages_pb);
goog.exportSymbol('proto.modlogie.keyvalue.KeyValue', null, global);
goog.exportSymbol('proto.modlogie.keyvalue.KeyValueReply', null, global);
goog.exportSymbol('proto.modlogie.keyvalue.KeyValuesReply', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.modlogie.keyvalue.KeyValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.modlogie.keyvalue.KeyValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.modlogie.keyvalue.KeyValue.displayName = 'proto.modlogie.keyvalue.KeyValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.modlogie.keyvalue.KeyValueReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.modlogie.keyvalue.KeyValueReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.modlogie.keyvalue.KeyValueReply.displayName = 'proto.modlogie.keyvalue.KeyValueReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.modlogie.keyvalue.KeyValuesReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.modlogie.keyvalue.KeyValuesReply.repeatedFields_, null);
};
goog.inherits(proto.modlogie.keyvalue.KeyValuesReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.modlogie.keyvalue.KeyValuesReply.displayName = 'proto.modlogie.keyvalue.KeyValuesReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.modlogie.keyvalue.KeyValue.prototype.toObject = function(opt_includeInstance) {
  return proto.modlogie.keyvalue.KeyValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.modlogie.keyvalue.KeyValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.modlogie.keyvalue.KeyValue}
 */
proto.modlogie.keyvalue.KeyValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.modlogie.keyvalue.KeyValue;
  return proto.modlogie.keyvalue.KeyValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.modlogie.keyvalue.KeyValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.modlogie.keyvalue.KeyValue}
 */
proto.modlogie.keyvalue.KeyValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.modlogie.keyvalue.KeyValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.modlogie.keyvalue.KeyValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.modlogie.keyvalue.KeyValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.modlogie.keyvalue.KeyValue.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.modlogie.keyvalue.KeyValue} returns this
 */
proto.modlogie.keyvalue.KeyValue.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.modlogie.keyvalue.KeyValue.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.modlogie.keyvalue.KeyValue} returns this
 */
proto.modlogie.keyvalue.KeyValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.toObject = function(opt_includeInstance) {
  return proto.modlogie.keyvalue.KeyValueReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.modlogie.keyvalue.KeyValueReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValueReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getFieldWithDefault(msg, 1, 0),
    keyValue: (f = msg.getKeyValue()) && proto.modlogie.keyvalue.KeyValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.modlogie.keyvalue.KeyValueReply}
 */
proto.modlogie.keyvalue.KeyValueReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.modlogie.keyvalue.KeyValueReply;
  return proto.modlogie.keyvalue.KeyValueReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.modlogie.keyvalue.KeyValueReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.modlogie.keyvalue.KeyValueReply}
 */
proto.modlogie.keyvalue.KeyValueReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.modlogie.messages.Error} */ (reader.readEnum());
      msg.setError(value);
      break;
    case 2:
      var value = new proto.modlogie.keyvalue.KeyValue;
      reader.readMessage(value,proto.modlogie.keyvalue.KeyValue.deserializeBinaryFromReader);
      msg.setKeyValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.modlogie.keyvalue.KeyValueReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.modlogie.keyvalue.KeyValueReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValueReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getKeyValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.modlogie.keyvalue.KeyValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional modlogie.messages.Error error = 1;
 * @return {!proto.modlogie.messages.Error}
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.getError = function() {
  return /** @type {!proto.modlogie.messages.Error} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.modlogie.messages.Error} value
 * @return {!proto.modlogie.keyvalue.KeyValueReply} returns this
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.setError = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional KeyValue key_value = 2;
 * @return {?proto.modlogie.keyvalue.KeyValue}
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.getKeyValue = function() {
  return /** @type{?proto.modlogie.keyvalue.KeyValue} */ (
    jspb.Message.getWrapperField(this, proto.modlogie.keyvalue.KeyValue, 2));
};


/**
 * @param {?proto.modlogie.keyvalue.KeyValue|undefined} value
 * @return {!proto.modlogie.keyvalue.KeyValueReply} returns this
*/
proto.modlogie.keyvalue.KeyValueReply.prototype.setKeyValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.modlogie.keyvalue.KeyValueReply} returns this
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.clearKeyValue = function() {
  return this.setKeyValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.modlogie.keyvalue.KeyValueReply.prototype.hasKeyValue = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.modlogie.keyvalue.KeyValuesReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.toObject = function(opt_includeInstance) {
  return proto.modlogie.keyvalue.KeyValuesReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.modlogie.keyvalue.KeyValuesReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValuesReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getFieldWithDefault(msg, 1, 0),
    keyValuesList: jspb.Message.toObjectList(msg.getKeyValuesList(),
    proto.modlogie.keyvalue.KeyValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.modlogie.keyvalue.KeyValuesReply}
 */
proto.modlogie.keyvalue.KeyValuesReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.modlogie.keyvalue.KeyValuesReply;
  return proto.modlogie.keyvalue.KeyValuesReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.modlogie.keyvalue.KeyValuesReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.modlogie.keyvalue.KeyValuesReply}
 */
proto.modlogie.keyvalue.KeyValuesReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.modlogie.messages.Error} */ (reader.readEnum());
      msg.setError(value);
      break;
    case 2:
      var value = new proto.modlogie.keyvalue.KeyValue;
      reader.readMessage(value,proto.modlogie.keyvalue.KeyValue.deserializeBinaryFromReader);
      msg.addKeyValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.modlogie.keyvalue.KeyValuesReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.modlogie.keyvalue.KeyValuesReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.modlogie.keyvalue.KeyValuesReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getKeyValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.modlogie.keyvalue.KeyValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional modlogie.messages.Error error = 1;
 * @return {!proto.modlogie.messages.Error}
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.getError = function() {
  return /** @type {!proto.modlogie.messages.Error} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.modlogie.messages.Error} value
 * @return {!proto.modlogie.keyvalue.KeyValuesReply} returns this
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.setError = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated KeyValue key_values = 2;
 * @return {!Array<!proto.modlogie.keyvalue.KeyValue>}
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.getKeyValuesList = function() {
  return /** @type{!Array<!proto.modlogie.keyvalue.KeyValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.modlogie.keyvalue.KeyValue, 2));
};


/**
 * @param {!Array<!proto.modlogie.keyvalue.KeyValue>} value
 * @return {!proto.modlogie.keyvalue.KeyValuesReply} returns this
*/
proto.modlogie.keyvalue.KeyValuesReply.prototype.setKeyValuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.modlogie.keyvalue.KeyValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.modlogie.keyvalue.KeyValue}
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.addKeyValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.modlogie.keyvalue.KeyValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.modlogie.keyvalue.KeyValuesReply} returns this
 */
proto.modlogie.keyvalue.KeyValuesReply.prototype.clearKeyValuesList = function() {
  return this.setKeyValuesList([]);
};


goog.object.extend(exports, proto.modlogie.keyvalue);
