version: '3.1'
services: 
  web:
    build: .
    container_name: ${app_name}
    restart: always
    volumes:
      - /data/${app_name}/files:/app/files
      - /data/${app_name}/configs:/app/configs   
    ports:
      - "${app_port}:443"
    environment:
      ASPNETCORE_URLS: "https://+"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${app_CertPwd}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "configs/app.pfx"
      CorsOrigins: "${app_CorsOrigins}"
      DefaultPassword: "${app_init_pwd}"
  db:
    image: mariadb
    container_name: ${app_name}_db
    restart: always
    volumes:
      - /data/${app_name}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${app_db_pwd:-123456}
