#!/bin/env bash

set -o errexit

scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$scripts_dir"

export IMAGE_USER=${IMAGE_USER:-modoth}
export IMAGE_VERSION=${IMAGE_VERSION:-latest}

methods=""

while :
do
    case $1 in
        prepare) methods="$methods prepare-build-image.sh";shift;;
        build) methods="$methods build-image.sh";shift;;
        push) methods="$methods push-image.sh";shift;;
        *) break;;
    esac
done

if [ -z "$methods" ];then
    methods="prepare-build-image.sh build-image.sh push-image.sh"
fi

for image in "$@"
do
    echo -e "\n==========  Handle ${image}  ==========\n"
    for method in $methods
    do
        ( cd $image && ./$method )
    done
done
