  SERVER_TYPE:
    image: ${docker_user}/modlogie_server_SERVER_TYPE:${app_version}
    container_name: ${app_name}_server_SERVER_TYPE
    restart: always
    volumes:
      - /data/${app_name}/files:/app/files
    environment:
      "ConnectionProps:Database": "${app_name}"
      "ConnectionProps:Password": "${db_pwd}"
      "User:Name": "${user_name}"
      "User:Password": "${user_pwd}"
      "File:ContentRoot": "/app"
      "File:Prefix": "files"
