FROM ubuntu:20.04

ARG HOST_NAME

RUN true \
&& export DEBIAN_FRONTEND=noninteractive \
&& sed -i -e 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
&& apt update && apt full-upgrade -y \
&& apt install -y \
    apt-transport-https \
    clang-format \
    curl \
    docker-compose \
    docker.io \
    mysql-client \
    openssh-server \
    redis-tools \
    software-properties-common \
    sudo \
    unzip \
    vim \
    zsh \
&& curl -sL 'https://getenvoy.io/gpg' | apt-key add - \
&& apt-key fingerprint 6FF974DB \
&& add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb focal stable" \
&& curl -sL https://deb.nodesource.com/setup_12.x | bash - \
&& apt install -y \
    getenvoy-envoy \
    nodejs \
&& rm -rf /var/lib/apt/lists/* \
&& mkdir /var/run/sshd \
&& useradd dev -G sudo,docker -m -s $(which zsh) \
&& su dev -c 'touch /home/dev/.zshrc' \
&& echo "dev:dev" | chpasswd \
&& echo "{\"hosts\": [\"tcp://${HOST_NAME}\"]}" > /etc/docker/daemon.json \
&& echo "export DOCKER_HOST=tcp://${HOST_NAME}:2375" >> /etc/environment \
&& mkdir -p /opt/protoc \
&& cd /opt/protoc \
&& curl -L 'https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-x86_64.zip' -o protoc.zip \
&& unzip protoc.zip \
&& curl -L 'https://github.com/grpc/grpc-web/releases/download/1.2.0/protoc-gen-grpc-web-1.2.0-linux-x86_64' -o bin/protoc-gen-grpc-web \
&& chmod -R 755 bin \
&& chmod -R +r include \
&& find include/ -type d -exec chmod +x {} \
&& sed -i -e 's/^PATH="/PATH="\/opt\/protoc\/bin:/' /etc/environment \
&& true

EXPOSE 22
CMD ["sh", "-c", "/usr/sbin/sshd -D"]

