FROM modlogie_dev_base:latest

RUN true \
&& curl https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O \
&& dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb \
&& apt update \
&& apt install -y \
    dotnet-sdk-3.1 \
&& rm -rf /var/lib/apt/lists/* \
&& true
